# Generated by Django 2.2.4 on 2021-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('formula', models.CharField(max_length=500)),
                ('propiedades', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rama', models.CharField(max_length=100)),
            ],
        ),
    ]
