# Generated by Django 2.2.4 on 2021-10-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rama',
            name='rama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
